# Generated by Django 6.0 on 2026-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '嵌入式'), (2, '前端'), (3, '后端'), (4, '生活')], null=True, verbose_name='文章分类'),
        ),
    ]
