# Generated by Django 6.0 on 2026-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '技术'), (2, '项目'), (3, '生活')], null=True, verbose_name='文章分类'),
        ),
    ]
