# Generated by Django 6.0 on 2026-09-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_articles_abstract_alter_articles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDraft',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, verbose_name='标题')),
                ('abstract', models.CharField(blank=True, max_length=150, verbose_name='文章简介')),
                ('content', models.TextField(blank=True, verbose_name='文章内容')),
                ('category', models.IntegerField(blank=True, choices=[(1, '技术'), (2, '项目'), (3, '生活')], null=True, verbose_name='文章分类')),
                ('pwd', models.CharField(blank=True, max_length=32, verbose_name='文章访问密码')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='草稿版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后保存时间')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='app01.articles', verbose_name='关联的正式文章')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_drafts', to='app01.cover', verbose_name='文章封面')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_drafts', to=settings.AUTH_USER_MODEL, verbose_name='草稿所有者')),
                ('tags', models.ManyToManyField(blank=True, related_name='article_drafts', to='app01.tags', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章草稿',
                'verbose_name_plural': '文章草稿',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='draft_owner_updated_idx')],
            },
        ),
    ]
