# Generated by Django 6.0 on 2026-09-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_articledraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='阅读时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='app01.articles', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章阅读记录',
                'verbose_name_plural': '文章阅读记录',
                'ordering': ('-viewed_at',),
                'indexes': [models.Index(fields=['article', '-viewed_at'], name='article_view_time_idx')],
            },
        ),
    ]
