# Generated by Django 6.0 on 2026-09-26 07:56

from django.db import migrations, models
from django.contrib.auth.hashers import identify_hasher, make_password


def hash_existing_article_passwords(apps, schema_editor):
    Articles = apps.get_model('app01', 'Articles')
    ArticleDraft = apps.get_model('app01', 'ArticleDraft')

    def ensure_hash(value):
        if not value:
            return value
        try:
            identify_hasher(value)
            return value
        except ValueError:
            return make_password(value)

    for article in Articles.objects.exclude(pwd__isnull=True).exclude(pwd='').iterator():
        article.pwd = ensure_hash(article.pwd)
        article.save(update_fields=['pwd'])

    for draft in ArticleDraft.objects.exclude(pwd='').iterator():
        draft.pwd = ensure_hash(draft.pwd)
        draft.password_action = 'set'
        draft.save(update_fields=['pwd', 'password_action'])


def clear_hashed_article_passwords(apps, schema_editor):
    """哈希不可逆；回滚字段长度前清空密码，避免截断为无效数据。"""
    Articles = apps.get_model('app01', 'Articles')
    ArticleDraft = apps.get_model('app01', 'ArticleDraft')
    Articles.objects.exclude(pwd__isnull=True).update(pwd=None)
    ArticleDraft.objects.update(pwd='', password_action='keep')


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledraft',
            name='password_action',
            field=models.CharField(choices=[('keep', '保持原密码'), ('set', '设置新密码'), ('remove', '移除密码')], default='keep', max_length=10, verbose_name='密码操作'),
        ),
        migrations.AlterField(
            model_name='articledraft',
            name='pwd',
            field=models.CharField(blank=True, max_length=128, verbose_name='文章访问密码'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pwd',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='文章密码'),
        ),
        migrations.RunPython(hash_existing_article_passwords, clear_hashed_article_passwords),
    ]
