# Generated by Django 6.0 on 2026-09-29 06:48

import django.db.models.deletion
import talks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='主题')),
                ('observed', models.TextField(blank=True, verbose_name='我看到了什么')),
                ('interest_reason', models.TextField(blank=True, verbose_name='为什么吸引我')),
                ('understanding', models.TextField(blank=True, verbose_name='我的理解')),
                ('open_questions', models.TextField(blank=True, verbose_name='还想知道什么')),
                ('source', models.TextField(blank=True, verbose_name='来源')),
                ('category', models.CharField(choices=[('unclassified', '未分类'), ('short', '短谈资'), ('serious', '严肃谈资'), ('daily', '日常谈资'), ('personal', '个性谈资')], default='unclassified', max_length=20, verbose_name='分类')),
                ('tags', models.JSONField(blank=True, default=list, validators=[talks.models.validate_tags], verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to=settings.AUTH_USER_MODEL, verbose_name='记录者')),
            ],
            options={
                'verbose_name': '谈资',
                'verbose_name_plural': '谈资',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='talks_talk_owner_i_5798c0_idx')],
            },
        ),
    ]
